sudo: required
services:
 - docker

before_install:
 - docker build -t omriwallach/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true omriwallach/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "aws-codestar-eu-central-1-697082700401"
  bucket_path: "docker"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
   secure: "$AWS_SECRET_KEY"